# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('info', models.CharField(max_length=2000)),
                ('menu_overview', models.CharField(max_length=200)),
                ('menu_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
